### ISSUE TITLE
ReferenceError: Cannot access 'latest' before initialization

### ISSUE THREAD

**Issue by Geod24** [mihails-strasuns/setup-dlang#19]
```
Run mihails-strasuns/setup-dlang@v0.4.1
ReferenceError: Cannot access 'latest' before initialization
    at /home/runner/work/_actions/mihails-strasuns/setup-dlang/v0.4.1/lib/compiler.js:150:87
    at Array.map (<anonymous>)
    at /home/runner/work/_actions/mihails-strasuns/setup-dlang/v0.4.1/lib/compiler.js:147:14
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/mihails-strasuns/setup-dlang/v0.4.1/lib/compiler.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
##[error]Cannot access 'latest' before initialization
##[error]Node run failed with exit code 1
```

https://github.com/mihails-strasuns/setup-dlang/blob/66261c5d1256f65ab63b0003e0bcd58def8750ef/lib/compiler.js#L150

@mihails-strasuns : `ldc-latest-ci` seems broken again, but this error is hiding the real error.

**Comment by Geod24** [comment]
Thanks! Can you make a release?

**Comment by mihails-strasuns** [comment]
https://github.com/mihails-strasuns/setup-dlang/releases/tag/v0.5.0

**Comment by Geod24** [comment]
Thanks!
